### ISSUE TITLE
Reddit Credentials Visible In Console Output

### ISSUE THREAD

**Issue by haydenk** [andrewbanchich/shreddit#103] opened 2024-08-15 20:53 UTC
>   2024-08-15T20:49:58.854510Z DEBUG  Sleeping for 2s to prevent rate limiting.
    at src/things/mod.rs:31
    in delete with self: Comment { id: "li5bmad", body: "The quick brown fox jumps over the lazy dog.", permalink: "/r/JoeRogan/comments/1es5t90/you_have_a_10_hour_flight_where_are_you_sitting/li5bmad/", source: Api { score: 1, created_utc: 1723674200.0, can_gild: false } }, config: Config { username: "\<redacted\>", password: "\<redacted\>", client_id: "\<redacted\>", client_secret: "\<redacted\>", dry_run: false, thing_types: [Posts, Comments], before: 2024-08-15T20:48:11.679292Z, max_score: None, replacement_comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", user_agent: "ShredditRustClient", gdpr_export_dir: None, edit_only: false }

More critically, the password is visible but the username, password, client_id, and client_secret are output multiple times in the console as it deletes.

The username would be helpful to see confirmation that it is working for the correct user but the other information should probably be hidden.

**Comment by andrewbanchich** [comment] 2024-08-15 22:28
Duplicate of https://github.com/andrewbanchich/shreddit/issues/60

See that thread for context.

Please let me know what specific security concerns you have with this.

-------- Original Message --------

**Closed** 2024-08-24 18:10 UTC
