### ISSUE TITLE
[Request] automatically create and updated logs as the script run

### ISSUE THREAD

**Issue by braboobssiere** [andrewbanchich/shreddit#95] opened 2024-01-25 15:19 UTC
create and updated a text file logs while the script is running (in case of something unexpected happened especially in GDPR mode) the user can continued where they left off (maybe max last 100 entries or something user can specific)

**Comment by andrewbanchich** [comment] 2024-01-27 01:16
duplicate of #49

**Closed by andrewbanchich** 2024-01-27 01:16 UTC
